[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.13",
    "base58>=2.1.1",
    "python-telegram-bot>=22.1",
    "requests>=2.32.4",
    "solana>=0.36.7",
    "telegram>=0.0.1",
]
